"""delete order-product-association table

Revision ID: 9c1d37c0a37e
Revises: 6ed828b1cc74
Create Date: 2026-02-04 22:01:16.132730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c1d37c0a37e"
down_revision: Union[str, Sequence[str], None] = "6ed828b1cc74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_product_association")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_product_association",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("order_id", sa.INTEGER(), nullable=False),
        sa.Column("product_id", sa.INTEGER(), nullable=False),
        sa.Column("count", sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
        sa.Column(
            "unit_price", sa.INTEGER(), server_default=sa.text("'0'"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_id", "product_id", name=op.f("idx_order_product_association")
        ),
    )
    # ### end Alembic commands ###
