"""delete user post relation

Revision ID: abc2eece2058
Revises: ae7e940d0a6f
Create Date: 2026-02-04 21:34:41.577436

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "abc2eece2058"
down_revision: Union[str, Sequence[str], None] = "ae7e940d0a6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_column("posts", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("user_id", sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, "posts", "users", ["user_id"], ["id"])

    # ### end Alembic commands ###
