"""add hashed_password to User

Revision ID: 006c4743b3da
Revises: c367ac47b5a0
Create Date: 2026-02-02 02:46:34.085039

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "006c4743b3da"
down_revision: Union[str, Sequence[str], None] = "c367ac47b5a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=128), nullable=True)
    )
    op.execute("UPDATE users SET hashed_password = '' WHERE hashed_password IS NULL")
    op.alter_column(
        "users", "hashed_password", existing_type=sa.String(length=128), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")

    # ### end Alembic commands ###
