"""user product relation

Revision ID: ae7e940d0a6f
Revises: 006c4743b3da
Create Date: 2026-02-02 03:09:23.414453

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae7e940d0a6f"
down_revision: Union[str, Sequence[str], None] = "006c4743b3da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("username", sa.String(length=20), nullable=False)
    )
    op.create_foreign_key(
        None, "products", "users", ["username"], ["username"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_column("products", "username")

    # ### end Alembic commands ###
