"""add email and active columns to users

Revision ID: d668958bc849
Revises: b12656159638
Create Date: 2026-02-05 01:54:57.512782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d668958bc849"
down_revision: Union[str, Sequence[str], None] = "b12656159638"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=128), nullable=True))
    op.add_column("users", sa.Column("active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "active")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
