"""rename_frist_name_to_first_name

Revision ID: 20331d9af841
Revises: fef52f6749ae
Create Date: 2026-01-18 23:59:25.253314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20331d9af841"
down_revision: Union[str, Sequence[str], None] = "fef52f6749ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profiles", sa.Column("first_name", sa.String(), nullable=True))
    op.drop_column("profiles", "frist_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profiles", sa.Column("frist_name", sa.VARCHAR(), nullable=True))
    op.drop_column("profiles", "first_name")
    # ### end Alembic commands ###
